### ISSUE TITLE
Add support for multiple keys in vault

### ISSUE THREAD

**Issue by cfinckler** [otto-de/edison-vault#2]
Vault is designed to store multiple keys below one path.
example: path/db-credentials user=hans password=wurst
This library expects, that the key always has the name "value" and that only one key is stored below a given path.

It would be nice, if it would be possible to access multiple keys below a single path.

For inspiration take a look at tesla-vault or turing-vault

**Comment by fhopeman** [comment]
Great idea, if you have implemented something like that, it would be great if you send a pull request. Otherwise, maybe we will look at that in the future.

**Comment by hgsy** [comment]
I am starting to work on this now.

**Comment by hgsy** [comment]
Code review/walkthrough welcome :)
#3

**Comment by fhopeman** [comment]
#3 merged
